config/routes.rb
Rails.application.routes.draw do

  resources :lessons
  resources :units
  resources :levels
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :unit
end

app/models/level.rb
class Level < ApplicationRecord
	has_many :units
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :level
  has_many :lessons
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_levels
  before_action :set_units
  before_action :set_lessons

  private 
  def set_levels
  	@levels = Level.all
  end

  def set_units
  	@units = Unit.joins(:level)
  end

  def set_lessons
  	@lessons = Lesson.joins(:unit)
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_levels
  before_action :set_units
  before_action :set_lessons

  def index
  	
  end

  private 
  def set_levels
  	@levels = Level.all
  end

  def set_units
  	@units = Unit.joins(:level)
  end

  def set_lessons
  	@lessons = Lesson.joins(:unit)
  end


end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:name, :unit_id)
    end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:name, :complete, :percent)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :level_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CourseWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="dashboard-main-wrapper">
  		<%= render 'partials/navbar'%>
  		<%= render 'partials/sidebar'%>
      <%= render 'partials/wrapper'%>
    	<%= render 'partials/footer'%>
    <div
    <script src="https://d3js.org/d3.v5.min.js"></script>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :lesson_name %>
  </div>

  <div class="field">
    <%= form.label :unit_id %>
    <%= form.text_field :unit_id, id: :lesson_unit_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.name %></td>
        <td><%= lesson.unit %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lesson.name %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @lesson.unit %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>

app/views/levels/_form.html.erb
<%= form_with(model: level, local: true) do |form| %>
  <% if level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :level_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <div class="actions">
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    <div>
    
  </div>

<% end %>

app/views/levels/edit.html.erb
<h1 class="card-header" >Editing Level</h1>

<%= render 'form', level: @level %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<h1 class="card-header" >Levels</h1>

<div class="table-responsive">
  <table class="table">
  <thead class="bg-light">
    <tr class="border-0">
      <th class="border-0">Name</th>
      <th class="border-0">Complete</th>
      <th class="border-0">Percent</th>
      <th colspan="3" class="border-0"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.name %></td>
        <td><%= level.complete %></td>
        <td><%= level.percent %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>


<br>

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<h1 class="card-header">New Level</h1>

<%= render 'form', level: @level %>

<%= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @level.name %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @level.complete %>
</p>

<p>
  <strong>Percent:</strong>
  <%= @level.percent %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>

app/views/partials/_footer.html.erb
<div class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                 Copyright © 2018 Concept. All rights reserved. Dashboard by <a href="https://colorlib.com/wp/">Colorlib</a>.
            </div>
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                <div class="text-md-right footer-links d-none d-sm-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/partials/_navbar.html.erb
<div class="dashboard-header">
    <nav class="navbar navbar-expand-lg bg-white fixed-top">
        <a class="navbar-brand" ><%= link_to "Course", root_path%></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto navbar-right-top">
                <li class="nav-item">
                    <div id="custom-search" class="top-search-bar">
                        <input class="form-control" type="text" placeholder="Search..">
                    </div>
                </li>
                <li class="nav-item dropdown notification">
                    <a class="nav-link nav-icons" href="#" id="navbarDropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span style="display: block; color: red" class="badge">10</span>
                        <i style="display: block; text-align: center;" class="fa fa-bell-o"></i> 
                        <!---<span class="indicator"></span>-->
                        
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right notification-dropdown">
                        <li>
                            <div class="notification-title"> Notification</div>
                            <div class="notification-list">
                                <div class="list-group">
                                    <a href="#" class="list-group-item list-group-item-action active">
                                        <div class="notification-info">
                                            <div class="notification-list-user-img">
                                            	<%= image_tag(image_path('avatar-2.jpg'), class: 'user-avatar-md rounded-circle')%>
                                            	<span>nombre</span>
                                            </div>
                                            <div class="notification-list-user-block"><span class="notification-list-user-name">Jeremy Rakestraw</span>accepted your invitation to join the team.
                                                <div class="notification-date">2 min ago</div>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#" class="list-group-item list-group-item-action">
                                        <div class="notification-info">
                                        	
                                            <div class="notification-list-user-img">
                                            	<%= image_tag(image_path('avatar-3.jpg'), class: 'notification-list-user-img')%>
                                            	<!--<img src="assets/images/avatar-3.jpg" alt="" class="user-avatar-md rounded-circle">-->
                                            </div>
                                            <div class="notification-list-user-block"><span class="notification-list-user-name">John Abraham </span>is now following you
                                                <div class="notification-date">2 days ago</div>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#" class="list-group-item list-group-item-action">
                                        <div class="notification-info">
                                            <div class="notification-list-user-img">
                                            	<%= image_tag(image_path('avatar-4.jpg'), class: 'user-avatar-md rounded-circle')%>
                                            	<!--<img src="assets/images/avatar-4.jpg" alt="" class="user-avatar-md rounded-circle">-->
                                            </div>
                                            <div class="notification-list-user-block"><span class="notification-list-user-name">Monaan Pechi</span> is watching your main repository
                                                <div class="notification-date">2 min ago</div>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#" class="list-group-item list-group-item-action">
                                        <div class="notification-info">
                                            <div class="notification-list-user-img">
                                            	<%= image_tag(image_path('avatar-5.jpg'), class: 'user-avatar-md rounded-circle')%>
                                            	<!--<img src="assets/images/avatar-5.jpg" alt="" class="user-avatar-md rounded-circle">-->
                                            </div>
                                            <div class="notification-list-user-block"><span class="notification-list-user-name">Jessica Caruso</span>accepted your invitation to join the team.
                                                <div class="notification-date">2 min ago</div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="list-footer"> <a href="#">View all notifications</a></div>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown nav-user">
                    <a class="nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    	<%= image_tag(image_path('user_icon_default.png'), class: 'user-avatar-md rounded-circle')%>
                        <% if user_signed_in? %>
                            <span class="ml-2"><%=current_user.email%></span>

                        <%end%>
                    	
                    </a>
                    <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                        
                            <% if user_signed_in?%>
                                
                                    <div class="progress blue">
                                        <span class="progress-left">
                                            <span class="progress-bar"></span>
                                        </span>
                                        <span class="progress-right">
                                            <span class="progress-bar"></span>
                                        </span>
                                    <div class="progress-value">90%</div>
                             
                                </h5>
                                <span class="status"></span>
                                <span class="ml-2">Available</span>
                            <%else%>
                                <h5 class="mb-0 text-white nav-user-name">
                                    <%= link_to "LogIn", new_user_session_path%> 
                                </h5>
                            <%end%>
                        </div>
                        <% if user_signed_in?%>
                            <a class="dropdown-item">
                                <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                            </a>
                        <%else%>
                            <a class="dropdown-item" >
                                <%= link_to "Sign up",new_user_registration_path %>    
                            </a>
                               
                        <%end%>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>

app/views/partials/_wrapper.html.erb
<div class="dashboard-wrapper">
    <div class="dashboard-ecommerce">
        <div class="container-fluid dashboard-content ">
            <!-- ============================================================== -->
            <!-- pageheader  -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="page-header">
                        <p class="notice"><%= notice %></p>
                        <p class="alert"><%= alert %></p>
                        <h2 class="pageheader-title">E-commerce Dashboard Template </h2>
                        <p class="pageheader-text">Nulla euismod urna eros, sit amet scelerisque torton lectus vel mauris facilisis faucibus at enim quis massa lobortis rutrum.</p>
                        <div class="page-breadcrumb">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">E-Commerce Dashboard Template</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- end pageheader  -->
            <!-- ============================================================== -->
            <div class="ecommerce-widget">
                <%= yield %>
                <!--<div class="row"></div>-->
            </div>
        </div>
    </div>
</div>

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-default">
    
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :unit_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :level_id %>
      <%= form.text_field :level_id, id: :unit_level_id, class: "form-control" %>
    </div>

    <div class="form-group">
      <div class="actions">
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
    
  </div>

<% end %>

app/views/units/edit.html.erb
<h1 class="card-header">Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1 class="card-header">Units</h1>

<div class="table-responsive">
  <table class="table">
  <thead class="bg-light">
    <tr class="border-0">
      <th class="border-0">Name</th>
      <th class="border-0">Level</th>
      <th colspan="3" class="border-0"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.level %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1 class="card-header">New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @unit.level %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>

app/views/welcome/index.html.erb
<h1>welcome</h1>